<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ctoutweb</groupId>
    <artifactId>argentDePoche</artifactId>
    <version>1.0.0-RC1</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <modules>
        <module>core</module>
        <module>infra</module>
        <module>application</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <profiles>
        <profile>
            <id>local</id>
            <properties>
                <!-- API version-->
                <api.version>v1</api.version>
                <api.version.path>/api/${api.version}</api.version.path>

                <!-- Database -->
                <database.schema>sc_argent_de_poche</database.schema>

                <!--Log -->
                <log.level>DEBUG</log.level>
                <log.file>logs/app.log</log.file>

                <!--Cors -->
                <cors.domains>http://localhost:4200,http://localhost:4200</cors.domains>

                <!--File-->
                <max.file.size>10MB</max.file.size>
                <is.file.to.compress>true</is.file.to.compress>

                <!--Image Path-->
                <default.image.extension>jpg</default.image.extension>
                <default.child.image.name>dtushfgld</default.child.image.name>
                <folder.path>C:/Programmation/java/argentDePoche/images</folder.path>

                <!--Horaire -->
                <zone.id>Europe/Paris</zone.id>

                <!--JWT -->
                <jwt.validity.hour>72</jwt.validity.hour>
                <jwt.issuer>ctoutweb_argent_de_poche</jwt.issuer>

                <!-- FrontEnd -->
                <front.end.base.url>http://localhost:4200</front.end.base.url>
                <qr.code.child.account.url>/compte/enfant/%s/info</qr.code.child.account.url>
            </properties>
        </profile>
        <profile>
            <id>moe</id>
            <properties>
                <!-- API version-->
                <api.version>v1</api.version>
                <api.version.path>/api/${api.version}</api.version.path>

                <!-- Database -->
                <database.schema>sc_argent_de_poche</database.schema>

                <!--Log -->
                <log.level>DEBUG</log.level>
                <log.file>logs/app.log</log.file>

                <!--Cors -->
                <cors.domains>http://localhost:4200,http://localhost:4200</cors.domains>

                <!--File-->
                <max.file.size>10MB</max.file.size>
                <is.file.to.compress>true</is.file.to.compress>

                <!--Image Path-->
                <default.image.extension>jpg</default.image.extension>
                <default.child.image.name>dtushfgld</default.child.image.name>
                <folder.path>/home/ubuntu/moe/argentDePoche/images</folder.path>

                <!--Horaire -->
                <zone.id>Europe/Paris</zone.id>

                <!--JWT -->
                <jwt.validity.hour>72</jwt.validity.hour>
                <jwt.issuer>ctoutweb_argent_de_poche</jwt.issuer>

                <!-- FrontEnd -->
                <front.end.base.url>http://52.47.100.124/argent-de-poche</front.end.base.url>
                <qr.code.child.account.url>/compte/enfant/%s/info</qr.code.child.account.url>

            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <!-- API version-->
                <api.version>v1</api.version>
                <api.version.path>/api/${api.version}</api.version.path>

                <!-- Database -->
                <database.schema>sc_argent_de_poche</database.schema>

                <!--Log -->
                <log.level>INFO</log.level>
                <log.file>logs/app.log</log.file>

                <!--Cors -->
                <cors.domains></cors.domains>

                <!--File-->
                <max.file.size>10MB</max.file.size>
                <is.file.to.compress>true</is.file.to.compress>

                <!--Image Path-->
                <default.image.extension>jpg</default.image.extension>
                <default.child.image.name>dtushfgld</default.child.image.name>
                <folder.path>/home/ubuntu/moe/argentDePoche/images</folder.path>

                <!--JWT -->
                <jwt.validity.hour>72</jwt.validity.hour>
                <jwt.issuer>ctoutweb_argent_de_poche</jwt.issuer>

                <!--Horaire -->
                <zone.id>Europe/Paris</zone.id>

                <!-- FrontEnd -->
                <front.end.base.url>http://52.47.100.124/argent-de-poche</front.end.base.url>
                <qr.code.child.account.url>/compte/enfant/%s/info</qr.code.child.account.url>
            </properties>
        </profile>
    </profiles>

</project>