spring.config.import=classpath:database.properties

#Pour l'acces aux image depuis un repertoir externe
folder.image.path=@folder.path@

# Version api
api.version=@api.version.path@

#Cors
cors.domains=@cors.domains@

# Image de default
default.child_image.name=@default.child_image.id@