# R2DBC connection
spring.r2dbc.url = ${DATABASE_URL_POCHE}
spring.r2dbc.username = ${DATABASE_USER_POCHE}
spring.r2dbc.password = ${DATABASE_PASSWORD_POCHE}
spring.jpa.properties.hibernate.default_schema: @database.schema@
# R2DBC pool Configuration
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-lifetime=60m